spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile