spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 290116955672-lt8mqdfgm6flh2t9nl3hkaqrsqeqf616.apps.googleusercontent.com
            client-secret: nT_FXs_rdy7tUmecMWZzvouf
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile